### ISSUE TITLE
How to do Pagination : Improve code

### ISSUE THREAD

**Issue by willysharp5** [dynamoosejs/dynamoose#614]
Here is my code 

Serveless Api Gateway 
```
user_list:
    handler: user/user_list.handler
    events:
      - http:
          path: user_list/userId/{userId}/limit/{limit}/lastkey/{lastkey}
          method: get
          cors: true
          parameters:
              paths:
                userId: true
                lastkey: true
                limit: true
          # authorizer: aws_iam

```

Api Call
```
https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/user_list/userId/user-123/limit/10/lastkey/start
```

Lambda NodeJs Code 
```
const { success, failure } = require('../libs/response-lib');
const pe          = require('parse-error');
const { User }    = require('../models/users');

const handler = async (event, context) => {
    const userId = event.pathParameters.userId;
    const lastkeyVal = event.pathParameters.lastkey;
    const limitVal = event.pathParameters.limit;
    

    //get from database
    try {
      
      let count = 0;
      let userList = [];
      let lastkeyBase64 = '';

      if (lastkeyVal === 'start') {
         userList = await User.scan().limit(limitVal).exec();
         //convert lastkey to base64
         if ( userList.lastKey ) {
            lastkeyBase64 = Buffer.from(JSON.stringify(userList.lastKey)).toString("base64");
         }else {
            lastkeyBase64 = 'end';
         }
         
         count = userList.count;

      }else if (lastkeyVal === 'end') {
         userList = [];
         count = 0;
      }else {
         //convert lastkey value whcih is base64 to json 
         let lastkeyJSON = JSON.parse(Buffer.from(JSON.stringify(lastkeyVal), 'base64').toString('utf-8'));

         //get from database where you left off 
         userList = await User.scan().startAt(lastkeyJSON).limit(limitVal).exec();
         count = userList.count;
         
         //check to see if lastkey exist 
         if ( userList.lastKey ){
            //convert lastkey to base64
            lastkeyBase64 = Buffer.from(JSON.stringify(userList.lastKey)).toString("base64");
         } else {
            lastkeyBase64 = 'end';
         }

      }


      let result = {
         "status":true,
         "userList": userList,
         "lastKey": lastkeyBase64,
         "count": count
      };

      console.log(` => USER LIST: [${JSON.stringify(result)}]`);
      return success(result);


    }catch (err) {
      let error = pe(err);
      console.error(' => LIMIT:', limit);
      console.error(' => LAST KEY:', lastkeyVal);
      console.error(' => ERROR:', error.stack);

      return failure({ status: false, error: "we encounter an internal error" });
    }

}

module.exports = {
   handler
}


```
