### ISSUE TITLE
Newly created items do not get stored in GSI

### ISSUE THREAD

**Issue by ablankenship10** [dynamoosejs/dynamoose#661]
### Summary:
Using dynamoose in a serverless application, where the dynamodb table is created using serverless.yml, creating a new item in the database does not allow me to query this item via the hashkey of a GSI. Dynamodb in AWS console shows 0 items in my GSI, however I'm aware that its possible that they only refresh that value every 6 hours. My query still does not return the expected record.

#### Model
```
dynamoose.setDefaults({
  prefix: process.env.TABLE_PREFIX,
  create: false,
  update: false,
});


const User = dynamoose.model('user', {
  id: {
    type: String,
    hashKey: true,
  },
  name: {
    type: String,
  },
  email: {
    type: String,
    index: {
      global: true,
      name: 'Auth',
      project: true
    }
  },
  password: {
    type: String
  },
});
```

#### Serverless.yml Table Creation
```
UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: Auth
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
```

#### Query
```
const email = 'mytestuser@example.com';
let user = await User.query('email').eq(email);
```

### Current output and behavior:

Query returns only {}

### Expected output and behavior:

Query should return my created user record with the email provided.

### Environment:

Operating System: Ubuntu linux locally (AWS Lambda)
Operating System Version: 18.04 locally (AWS Lambda)
Node.js version (`node -v`):  12.6.0 locally (Lambda running with 10.x)
NPM version: (`npm -v`): 6.9.0
Dynamoose version: 1.10.0
Dynamoose Plugins:

-

### Dynamoose Plugins:

- [ ] Yes, I believe that one or multiple 3rd party Dynamoose plugins are effecting this issue
- [ ] No, I believe this issue is independent of any 3rd party Dynamoose plugins I'm using
- [ ] Unknown, I'm unsure if Dynamoose plugins are effecting this issue
- [X] I am not using any Dynamoose plugins

### Other information (if applicable):

Marked as bug and question as surely I'm doing something incorrectly, but just incase there is a bug. Is it possible this ORM is not meant to be used in serverless? Also documentation on the website seems outdated.

### Type (select 1):
- [X] Bug report
- [ ] Feature suggestion
- [X] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [X] I have read through the Dynamoose documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [X] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [X] I have tested the code provided and am confident it doesn't work as intended
- [X] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [X] I have filled out all fields above
- [X] I am running the latest version of Dynamoose
