### ISSUE TITLE
Having an issue with Query on index

### ISSUE THREAD

**Issue by Zanndorin** [dynamoosejs/dynamoose#704]
### Summary:
Hi, I have an issue with querying an index. I have tried to debug for a long time now but I am not getting anywhere. Every query but the one on the sraCode-index work. I'm trying with Query or QueryOne most of the time it looks like this:

```
.queryOne({ sraCode })
      .using('sraCode-index')
      .exec()
```

**I'm creating my DynamoDB with Cloudformation.** 

Thankful for all help :(

EDIT:
Fighting a bit more I found this culprit.
```
{
    subCategoryId: '549FC2',
    sraCode: '0706440',
    id: '270091',
    catClassId: '8516440',
    [Symbol(originalItem)]: {
      subCategoryId: '549FC2',
      sraCode: '0706440',
      id: '270091',
      catClassId: '8516440'
    }
``` 

#### Cloudformation 
```
Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'subCategoryId'
          AttributeType: 'S'
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'catClassId'
          AttributeType: 'S'
        - AttributeName: 'country'
          AttributeType: 'S'
        - AttributeName: 'sraCode'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'subCategoryId'
          KeyType: 'HASH'
        - AttributeName: 'id'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: 'unique-catclass-index'
          KeySchema:
            - AttributeName: 'id'
              KeyType: 'HASH'
          Projection:
            ProjectionType: 'ALL'
        - IndexName: 'catClassId-country-index'
          KeySchema:
            - AttributeName: 'catClassId'
              KeyType: 'HASH'
            - AttributeName: 'country'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'
        - IndexName: 'sraCode-index'
          KeySchema:
            - AttributeName: 'sraCode'
              KeyType: 'HASH'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes:
              - 'id'
              - 'catClassId'
              - 'subCategoryId'
```

#### Schema
```
country: {
    type: String,
    enum: ['SE', 'NO', 'FI', 'EN', 'EE', 'LT', 'LV', 'PL', 'SK', 'CZ'],
    required: true,
  },
  catClassId: {
    type: String,
    required: true,
    index: {
      global: true,
      name: 'catClassId-country-index',
      project: true,
      rangeKey: 'country',
    },
  },
  id: {
    type: String,
    required: true,
    rangeKey: true,
    index: {
      global: true,
      name: 'unique-catclass-index',
      project: true,
      throughput: 5,
    },
  },
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    get: detectNull,
  },
  shortDescription: {
    type: String,
    get: detectNull,
  },
  longDescription: {
    type: String,
    get: detectNull,
  },
  keywords: {
    type: String,
    get: detectNullReturnEmptyString,
  },
  documents: {
    type: 'list',
    list: [DocumentDefinition],
  },
  images: {
    type: 'list',
    list: [String],
  },
  price: {
    type: String,
    get: detectNull,
  },
  specifications: {
    type: 'list',
    list: [SpecificationDefinition],
  },
  subCategoryId: {
    type: String,
    required: true,
    hashKey: true,
  },
  disabled: {
    type: Boolean,
    required: true,
  },
  sraCode: {
    type: String,
    get: detectNull,
    index: {
      global: true,
      name: 'sraCode-index',
      project: ['catClassId', 'id', 'subCategoryId', 'sraCode'],
    },
  },
  make: {
    type: String,
    get: detectNull,
    // Doesn't exist in all countries yet
    // required: true,
  },
  model: {
    type: String,
    get: detectNull,
    // Doesn't exist in all countries yet
    // required: true,
  },
  accessories: {
    type: 'list',
    list: [String],
  },
  sortIndex: {
    type: Number,
  },
}
```

#### Model
```
dynamoose.model(<PRODUCTS_TABLE_NAME>, <SeeAbove> {
  create: false,
  update: false,
  waitForActive: false,
})
```

### Type (select 1):
- [ ] Bug report
- [ ] Feature suggestion
- [X] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [X] I have read through the Dynamoose documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [X] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [X] I have tested the code provided and am confident it doesn't work as intended
- [X] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [X] I have filled out all fields above
- [X] I am running the latest version of Dynamoose
